site_name: Learn Agentic AI from Low Code to Code - Documentation
site_url: https://sitename.example
theme:
  name: material
  font:
    # text: default
    code: Red Hat Mono
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  features:
    - navigation.footer

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: Copyright &copy; 2025 Panaversity. All rights reserved.

repo_url: https://github.com/panaversity/learn-agentic-ai-from-low-code-to-code

extra:
  social:
    - icon: material/facebook
      link: https://facebook.com/panaversity/
    - icon: material/instagram
      link: https://www.instagram.com/panaversity/?igsh=cmljY3A2bmcyNzl3#
    - icon: material/youtube
      link: https://www.youtube.com/channel/UCV1ZbnHzA7FwG7XXYYzE84w
    - icon: material/linkedin
      link: https://www.linkedin.com/company/panaversity/posts/?feedView=all